# Generated by Django 5.0.6 on 2024-07-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_bloking',
            field=models.TextField(default=''),
        ),
    ]
