# Generated by Django 5.0.6 on 2024-06-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_userpro_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpro',
            name='token_access',
        ),
    ]
