# Generated by Django 5.0.6 on 2024-06-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_userpro_first_name_userpro_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='photo_profile',
            field=models.ImageField(default='User_profile/default_profile.png', upload_to='User_profile'),
        ),
    ]
