# Generated by Django 5.0.6 on 2024-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0009_userpro_lose_userpro_score_userpro_win'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.CharField(blank=True),
        ),
    ]
