global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'authdb'
    static_configs:
      - targets: ['authdb:5432']
  - job_name: 'gamedb'
    static_configs:
      - targets: ['gamedb:5432']
  - job_name: 'trackdb'
    static_configs:
      - targets: ['trackdb:5432']
  - job_name: 'chatdb'
    static_configs:
      - targets: ['chatdb:5432']

