# Generated by Django 5.0.6 on 2024-06-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_customuser_unigue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unigue_id',
            field=models.IntegerField(default=0),
        ),
    ]
