# Generated by Django 5.0.6 on 2024-06-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_friends_requsets'),
    ]

    operations = [
        migrations.AddField(
            model_name='requsets',
            name='photo_profile',
            field=models.ImageField(default='User_profile/default_profile.png', upload_to='User_profile'),
        ),
    ]
