# Generated by Django 5.0.6 on 2024-06-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_requsets_photo_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requsets',
            new_name='FriendRequest',
        ),
    ]
