# Generated by Django 5.0.6 on 2024-07-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_customuser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='Untitled', max_length=10),
        ),
    ]
