# Generated by Django 5.0.6 on 2024-07-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_online',
            new_name='available',
        ),
    ]
