# Generated by Django 5.0.6 on 2024-07-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_match',
        ),
    ]
