# Generated by Django 5.0.7 on 2024-07-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_profile',
            field=models.ImageField(default='User_profile/avatar.svg', upload_to='User_profile'),
        ),
    ]
