# Generated by Django 5.0.7 on 2024-07-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='intraUser',
            field=models.BooleanField(default=False),
        ),
    ]
