# Generated by Django 5.0.7 on 2024-07-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_customuser_intrauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='Untitled', max_length=10),
        ),
    ]
