# Generated by Django 5.0.7 on 2024-07-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_customuser_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='intraUser',
        ),
    ]
