# Generated by Django 5.0.6 on 2024-07-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_conversation_user_bloking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='room_name',
            field=models.TextField(default=''),
        ),
    ]
