# Generated by Django 5.0.7 on 2024-07-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_alter_conversation_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_msg',
            field=models.BooleanField(default=False),
        ),
    ]
