# Generated by Django 5.1.1 on 2024-09-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0004_message_read_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user_bloking',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
