# Generated by Django 5.1.1 on 2024-09-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_alter_conversation_user_bloking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user_bloking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
